### ISSUE TITLE
Plans for a 1.7.9 upgrade?

### ISSUE THREAD

**Issue by Katelyn-SN** [Poweruser/MinetickMod#1]

**Comment by Poweruser** [comment]
Counter question: Is somebody actually using my modifications/working with the code? If so, I'd like to hear/read about it, as it has been awfully quiet so far. Except for a few people who approached me, just wanting this or that.
I don't really see a reason for continuing on if nobody is interested. And by "interested" I mean more than just expecting a working server kernel and running it without giving any feedback. Bug reports and maybe a little research/coding help would be nice.

**Comment by Zilacon** [comment]
@Poweruser I would love to use your project if it supported MCPC+.
I left a comment on your other project page here: https://github.com/Poweruser/MinetickMod-1.6.x/issues/2

I test and report issues on many mods, plugins, and projects on TickThreading alone ive reported over 40 issues. I do not however edit code in any way.

**Comment by vmarchaud** [comment]
Hi PowerUser, i had talk with you like one month ago and we say recontact in one month, so i tryied to contact u but got no response by mail.
Can you pliz check your mail and awnser please.
Thanks

**Comment by Katelyn-SN** [comment]
Update was completed, Ticket Closed

**Comment by Poweruser** [comment]
It wasn't complete yet. Just added two more important features to the v1.7.9 branch:
https://github.com/Poweruser/MinetickMod/commit/2eca777c5f3490c6468dbf5705b96fdc944030b8 (an autosave that does not put the main thread to sleep while the files are written to the disk) and
https://github.com/Poweruser/MinetickMod/commit/8a756663eb44067c7809693915af23988c85752d (offloaded path searches of subtypes of EntityCreature to other threads [which finally makes fighting lots of mobs at the same time enjoyable])
