### ISSUE TITLE
Updated 1.6.4 branch?

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#10]
I know this may be asking a lot from you and i completely understand if you cant do this.

But i would like to request a updated 1.6.4 Minetick jar so i can create a hub for my server network.
By updated i mean all the optimizations and improvements you have done to the 1.7.9 branch into the 1.6.4 branch.

If you could do this it would help so much!
Thanks!

**Comment by Poweruser** [comment]
That shouldn't be too difficult to do, but not right away.
I'm currently in the middle of two other plugin projects that I want to get somewhat up and running before I get to this task

**Comment by Zilacon** [comment]
Thats great! Thanks a lot!

Take your time i appreciate the work you do on this. I am still waiting on technic to update Hexxit and Voltz to 1.6.4 so i can make my entire modded network run off a hub.

This shouldn't have any problems using bungeecord to go to a MCPC server would it? Never did bungeecord so i figured id ask while i am ahead. I wanted the hub to basically be a 1.6.4 hub/survival/mini-games server that links with the modded servers of mine through bungeeportals. Can this be done through minetick?

**Comment by Katelyn-SN** [comment]
@Zilacon It works fine i've used a MineTick server as my lobby server with portals that connect you to MCPC/Cauldron servers.

**Comment by Poweruser** [comment]
Should be all in, except for a few of the debug commands and the customizable ore rates. If you need any of those as well, let me know.
It would be nice, if you could get Maven3 and the JDK, clone the repo, checkout the branch and compile it yourself.

**Comment by Zilacon** [comment]
Yeah well i dont know the first thing about java let alone compiling something >_>

**Comment by Poweruser** [comment]
Alright, it's in the releases. And you might want to run it on a test server first, I didn't do much testing of it myself

**Comment by Zilacon** [comment]
One of my devs compiled a version, but it was at like 0 tps when it started up o_O
Thanks, ill use your version.

**Comment by Zilacon** [comment]
Yeah his compile must have been messed up or something.
His took 19 seconds to start, no plugins, already had worlds just needed to load them.
Yours took 7.1 seconds.

Thanks again!

**Comment by Poweruser** [comment]
He's probably hasn't pulled the changes from today yet. The entities not doing anything was because of this: 6a8b8a8
