### ISSUE TITLE
Servers timing out at initial startup.

### ISSUE THREAD

**Issue by Tekfur** [Poweruser/MinetickMod#15]
While testing a bungee cord server setup I received this error at initial startup, afterwards I could use Advanced Portals to connect to all worlds and the /server commands worked fine.

bbff":985 by SpigotMC
13:30:39 [INFO] Enabled plugin cmd_send version git:cmd_send:1.7-SNAPSHOT:"e99bb
ff":985 by SpigotMC
13:30:39 [INFO] Enabled plugin cmd_list version git:cmd_list:1.7-SNAPSHOT:"e99bb
ff":985 by SpigotMC
13:30:39 [INFO] Listening on /0.0.0.0:25577
13:31:01 [INFO] [/192.168.254.1:49779] <-> InitialHandler has connected
13:31:02 [INFO] [VinyI_Scratch] <-> InitialHandler has connected
13:31:04 [INFO] [VinyI_Scratch] <-> ServerConnector [lobby] has connected
13:31:14 [INFO] [VinyI_Scratch] <-> ServerConnector [server1] has connected
13:31:16 [INFO] [VinyI_Scratch] <-> ServerConnector [server2] has connected
13:31:19 [INFO] [VinyI_Scratch] <-> ServerConnector [server3] has connected
13:31:44 [WARNING] [VinyI_Scratch] <-> ServerConnector [server1] - read timed ou
t
13:31:44 [INFO] [VinyI_Scratch] <-> ServerConnector [server1] has disconnected
13:31:46 [WARNING] [VinyI_Scratch] <-> ServerConnector [server2] - read timed ou
t
13:31:46 [INFO] [VinyI_Scratch] <-> ServerConnector [server2] has disconnected
13:31:49 [WARNING] [VinyI_Scratch] <-> ServerConnector [server3] - read timed ou
t
13:31:49 [INFO] [VinyI_Scratch] <-> ServerConnector [server3] has disconnected
13:32:19 [INFO] [VinyI_Scratch] <-> ServerConnector [server1] has connected
13:32:19 [INFO] [VinyI_Scratch] <-> DownstreamBridge <-> [lobby] has disconnecte
d

**Comment by Poweruser** [comment]
Which server version did you use for this test? 1.7.10?
As this is the bungee log, what did the servers log about these player connections?

**Comment by Tekfur** [comment]
1.7.10 R01 Snapshot is the version I used, and the server 1,2,and 3 logged no connections during this time

**Comment by Poweruser** [comment]
Ok, I'll do some testing myself and see why the connection fails on the first attempt

**Comment by Poweruser** [comment]
This problem was already known and fixed in Spigot [[link]](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/f48f848b8124dfd496e978a9976ed4797fe0efb7). I added their fix here. All versions since 1.7.9 seem to be affected.
