### ISSUE TITLE
Connection reset by peer when connecting to server.

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#16]
So using the 1.7.10 version with bungee setup. When i connect to the server everythings working fine.

When i go to do /server servername to connect to another server it connects me to the server for maybe half a second and then disconnects me saying "connection reset by peer".

This is being used to do Bungee -> Minetick -> KCauldron 1.7.10.
Any idea what im doing wrong and how to fix this?
All servers are in offline mode.
All servers have connection-throttle to -1.
All servers have bungee support enabled.

**Comment by Zilacon** [comment]
I made a issue on bungeecord as well here: https://github.com/SpigotMC/BungeeCord/issues/1483

One thing is for sure, MineTick atleast allows modded clients to join it, while spigot does not. However it would be nice if i could connect to the cauldron servers as well but i am unsure as to what is causing this issue.

**Comment by Poweruser** [comment]
I'm afraid I don't have a solution, rather a list of suggestions on how to further narrow down the issue.
- recheck the port configurations of the connected server. Make sure that no port is assigned twice and none of them is already used by another program
- Remove the MinetickMod server from your test setup and replace it by a second cauldron ~~or spigot server~~ (I forgot that Spigot wont let you connect at all, btw I have no clue why MinetickMod let's you then) and see if the issue still persists
- Also try your setup with just MinetickMod servers, and see if that would work

According to your ticket at BungeeCord, this seems to be a problem between Bungee and the modded server

> This happens on multiple modpacks, to multiple players. The bungee/vanilla server works perfectly fine when simply connecting to the vanilla part its just trying to get to the cauldron part thats bugging out.

**Comment by Zilacon** [comment]
Yes but since MineTick worked correctly i figured there was a chance you would know whats going on and fix it. I got more faith in you then anyone over at spigot when they cant even get their own stuff to work together heh...

**Comment by Zilacon** [comment]
Turns out Yive on Yives mirror fixed Spigot's connection problem for me that MineTick didnt have.
I guess spigot tries to assign too many channels while the channel limit is 128? Not sure if MineTick has anything like this or not.

**Comment by Poweruser** [comment]
> I guess spigot tries to assign too many channels

Not Spigot, rather i guess the mods that are loaded the client (or maybe on the cauldron server) are registering so many plugin channels. This check that devryb had pointed out (which MinetickMod does not have) was presumably put there as a precaution against misuse or overload, which is fine. The set value (max 128 channels) was just too tight for your case. Would be nice if it was configurable.

So, does it work now with Spigot as the Lobby server, or can you still not connect to the cauldron server?

**Comment by Zilacon** [comment]
I can connect to spigot now but i cannot connect to cauldron.
I made a issue report to prototik here:
https://prok.pw/gitlab/Prototik/KCauldron/issues/5

Provided what little info i had, i just want to get this working and idk whats causing it to not connect.
And since chococraft was in the error i attempted to remove that from the server and it still dont work so its not that. I guess it checks all player entities like how Galacticraft does.

**Comment by Poweruser** [comment]
Well I guess that takes me out of the equation, as MinetickMod is not part of your bungee setup anymore and it is still not working. I'm sorry that I'm not able to help you there. I haven't worked with Forge and/or modded servers and my knowledge on BungeeCord won't probably be enough to solve it. Good luck then.

**Comment by Zilacon** [comment]
Yeah i went back to MineTick after i confirmed Spigot had the same issue once i was able to connect.
Seems to be a bungee/cauldron issue but only one working on cauldron these days is prototik so hes my only hope at this point :(

**Comment by Poweruser** [comment]
The stack trace you get on the cauldron server sadly wont point to the cause as it happens during the logout, which makes it a consequential error:

> at chococraft.common.events.ChocoboPlayerTracker.onPlayerLogout(ChocoboPlayerTracker.java:73) [ChocoboPlayerTracker.class:?]
> ...
> at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:575) [FMLCommonHandler.class:KCauldron-1.7.10-4.1403.69]

**Comment by Zilacon** [comment]
Thats the only errors i get sadly :(

**Comment by Poweruser** [comment]
What one (Prototik, I guess) has to do now is
- to figure out what reference is null at this point:

> java.lang.NullPointerException
> at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:109) ~[FMLOutboundHandler$OutboundTarget$4.class:KCauldron-1.7.10-4.1403.69]
- and then track down what must have happened, or rather what did not happen in order for that reference to be null, which can be very vague and speculative

Another approach is manual testing and live debugging, which only someone could do who knows what he has to look for
