### ISSUE TITLE
Need another build of 1.6.4

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#20]
Hello im starting up a 1.6.4 HUB and like im using MineTick for my 1.7.10 HUB i want to do the same with the 1.6.4 one. However it looks like there are no compiled builds for it in the release section.

Wondering if you could make a build again? And if possible add any updated changes since the last build to it? If you cant i understand.

Also since ive never tried this with MT 1.6.4 is it compatible with BungeeCord?

Thanks again!

**Comment by Poweruser** [comment]
It's up.
Also noticed that the client view distance feature wasn't working properly. That's fixed now and it got a setting as well.

>  is it compatible with BungeeCord?

It wasn't before, but it is now

**Comment by Zilacon** [comment]
Thank you very much!
