### ISSUE TITLE
Error opening MySQL connection

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#21]
So i just got to setting this up on my actual server, had to reinstall OS. Anyways whenever it starts it shows this and AutoRank errors afterwards. Ive changed AutoRank's version 5 times its like that on every version.

```
01:25:32 [INFO] Bukkit version format changed. Version not checked.
01:25:32 [INFO] MinetickMod-1.6.4-R2.0-90-g2c35926 (MC: 1.6.4)
01:25:32 [INFO] 1.6.4-R2.0
01:25:32 [INFO] Error opening MySQL connection!
01:25:32 [INFO] [Vault][Economy] Essentials Economy hooked.
01:25:32 [INFO] Essentials: Using GroupManager based permissions.
01:25:32 [INFO] [EssentialsChat] Enabling EssentialsChat v2.12.2
01:25:32 [INFO] [Autorank] Enabling Autorank v2.7.2 Beta
01:25:32 [INFO] [Autorank] Simple config file loaded
01:25:32 [INFO] [Autorank] Advanced config file loaded
01:25:32 [INFO] [Autorank] New playerdata.yml file loaded. AR can keep track of player progress now!
01:25:32 [SEVERE] Error occurred while enabling Autorank v2.7.2 Beta (Is it up to date?)
java.lang.NullPointerException
    at me.armar.plugins.autorank.mysql.wrapper.MySQLWrapper.sqlSetup(MySQLWrapper.java:80)
    at me.armar.plugins.autorank.mysql.wrapper.MySQLWrapper.<init>(MySQLWrapper.java:35)
    at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:107)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugin(CraftServer.java:292)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.enablePlugins(CraftServer.java:274)
    at net.minecraft.server.v1_6_R3.MinecraftServer.l(MinecraftServer.java:364)
    at net.minecraft.server.v1_6_R3.MinecraftServer.f(MinecraftServer.java:341)
    at net.minecraft.server.v1_6_R3.MinecraftServer.a(MinecraftServer.java:301)
    at net.minecraft.server.v1_6_R3.DedicatedServer.init(DedicatedServer.java:155)
    at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:477)
    at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
```

**Comment by Poweruser** [comment]
Check the config file `\plugins\Autorank\AdvancedConfig.yml` for syntax errors and check if the `sql` section is missing.

from MySQLWrapper.java:

> 77: public void sqlSetup(SimpleYamlConfiguration config) {
> 78: ConfigurationSection s = config.getConfigurationSection("sql");
> 79:
> 80: Boolean enabled = s.getBoolean("enabled");
> 81: if (enabled != null && enabled) {

When the section "sql" does not exist in this config file, or can not be accessed, then the variable s is null and the call getBoolean in line 80 throws a null pointer exception

Also: When you copied the file over, using a different user account than the one that the server is run under, did you give the the executing account the access permissions?

**Comment by Zilacon** [comment]
The advanced config has no syntax errors, just checked on yamlint.com.

The sql section is there and everything is set correctly to connect to the server.

Just checked the permissions for the plugins and configs and everything has r/w access.

**Comment by Poweruser** [comment]
Then I'm clueless. There must be something else that prevents the config from being loaded.
Generate new config files and copy over the individual sections one by one, instead of the whole content.

**Comment by Zilacon** [comment]
...
I re-spaced out the sql section and now it works (facedesk)

Before it was like:

```
sql:
                                      username:
                                      name:
```

now its:

```
 sql:
  username:
  name:
```

And now it works... At this point im just gonna say it. I hate YAML.

**Comment by Zilacon** [comment]
Sorry for wasting your time again.

**Comment by Poweruser** [comment]
Don't worry. I prefer little noises like this over deafening silence. Glad that I could help

**Comment by Zilacon** [comment]
Question, how much would you charge me to make plugins for my network?
Or is that something your not interested in doing?

**Comment by Zilacon** [comment]
Just wondering would you be willing to help make plugins for my network? Or would you like to be paid for doing so? Or your not interested in doing such a thing.

**Comment by Poweruser** [comment]
Neither. And it's not money what I am after. What would be great was somebody who did have interest in the projects that I already have and help me to get them done. I basically just came from a server, that I had done a lot of the plugin work for (roughly two years; the one I created this server mod for). I don't thing I want to do this anytime soon again. Thx for the offer but I'd like to stay independent for now

**Comment by Zilacon** [comment]
Well if i did not take an interest i wouldn't be using minetick. Ive been using it since your 1.5.2 build.
Just i have 4 unfinished plugins wasting away and i need someone whos experienced to help finish them and not have to worry about them stealing the plugin for their self. Every programmer ive had but Wix0a a 10 year old programmer has stolen any plugin i asked to help program and debranded it and claimed it as their own. Even when 80% of the code was not even theirs.

I have a large network of servers and very little people to help me get stuff done or to rely on. Its why i asked you because anytime im having a problem i post here and you are instantly there to guide me on what could be the problem or how to solve it. You do not push people away for not understanding something or being an annoyance.
