### ISSUE TITLE
Issue with votifier?

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#5]
Me and my staff have been updating all of our listings on vote sites. I run 11 servers 10 of them are modpack servers running old MCPC jars with TickThreading.

Those servers work fine. Votifier packets go through, connects fine, and votes go through fine.

Votifier shows green in the plugins list so it is loaded for MineTick 1.7.9 however every time we try to test it on any website it does not go through. The ports are set on all firewalls correctly and the RSA key being used is correct as well.

The only thing i can think of is the problem would be MineTick. I cannot go and download another version though due to the DMCA.

Any ideas?

**Comment by Poweruser** [comment]
Votifier creates its own tcp socket, it is listening on for incoming connections from the votes sites. The socket is initialized when the plugin is loaded (in onEnable()) and prints a info log message ("Votifier enabled.") when that is done without errors. The incoming connections are being accepted and processed in a new thread that Votifier creates. Once a incoming vote is received the the Votifier's debug setting is enabled, then it prints another log message ("Received vote record -> " + vote), before processing the VoteListeners and then firing a VotifierEvent afterwards.  
When the plugin was successfully loaded, all this so far happens independently from the rest of the server. I don't see where my changes can possibly interfere here.       

The host address, that the socket is bound to, is read from the config file `server.properties` from the setting `server-ip`. If the reading failed, or no address is set there, then Votifier defaults to the host address `0.0.0.0`, which binds the socket to all available IPv4 network interfaces. This should not, but could be a problem in your case, please check that.           

The port, that the socket is bound to, is read from Votifier's config file. If none is set there Votifier uses the port 8192 by default there

**Comment by Zilacon** [comment]
All of my servers have the server-ip blank as when i set the ip it has issues binding to the port.

The port for my bukkit server is set to 10010

**Comment by Zilacon** [comment]
The votifier port i mean.

**Comment by Poweruser** [comment]
I'm sorry but I can't find anything in my changes that would interfere with Votifier to the extend, that it is prevented from receiving incoming connections.  
That's why I am looking for the fault in Votifier. On that note, the last released version was for 1.6.2 and the last update on their repository was for 1.7.2. Maybe it just needs to be recompiled for 1.7.9?  
Edit: What about the log messages that I mentioned? What is written to the server log with Votifier's debug setting enabled?  
Edit2: What it could be, is the yet incomplete BungeeCord support in MinetickMod. I didn't change the API yet, to pass the player's real IP inside the PlayerLoginEvent. That means that MinetickMod and the loaded plugins only see the proxy's IP as the player IP, and not the real one. So when you handle the vote through a VoteHandler or the VoteEvent and the source IP is checked against the player's IP, it would fail there. But before we go there, I want a confirmation from you, that Votifier does receive the incoming connections from the vote sites and prints "Received vote record ->  ... " in the server log, when the its debug setting is enabled

**Comment by Zilacon** [comment]
The debug is enabled on all votifier's on all my servers.

Whenever someone votes for the server nothing shows on console at all.

But when we "test" the votifier information on a vote site like planet minecraft it succeeds the test so votifier is receiving and sending back a confirmation packet for the vote sites but whenever a vote is coming in nothing happens.

We got our own custom economy plugin APOC Payday which handles all the vote rewards. The same version is running on all the other servers and votes are coming through and our economy plugin is rewarding for the votes. So its not that.

To test the rewards i also threw in VotifierScripts. This was the old way i used to reward for voting and that did not work either.

I am running out of ideas.

**Comment by Poweruser** [comment]
Has the issue been resolved? Or at least the reason for it been found? If so I'd like to know about it

**Comment by Zilacon** [comment]
No i dont know what the issue is and neither did you so i just decided to close it.

It might just be votifier being outdated.

BTW have you implemented the stuff i mentioned in my other issue? From EVOC?

**Comment by Poweruser** [comment]
Hmm, maybe I update votifier to 1.7.9 and add in more debug messages to find what is not working

**Comment by Poweruser** [comment]
Try this: https://github.com/Poweruser/votifier/releases/tag/debuggingtest1_1.7.9
And copy all it's log messages here (the ones starting with [Votifier]), or as issue over there: https://github.com/Poweruser/votifier/issues

Apart from adding more debug messages, I've also given each connecting client a separate thread, so if 2 votes are coming in in quick succession, the 2nd one doesn't have to wait for the first one to finish processing.

**Comment by Zilacon** [comment]
So i put it in, restarted the server...
Tried voting on TOPG.org, nothing happend on console. Checked the RSA and Port everything matches. Checked the port forwarding on linux firewall and router, everything matches.

Tried voting again on MC Index http://prntscr.com/4p3xxb
Only thing i got was this: [16:40:55 INFO]: net.minecraft.util.com.mojang.authlib.GameProfile@fc1ab7b[id=<null>,name=MCI,properties={},legacy=false](/198.27.83.157:43957) lost connection: Disconnected

Debug is set to true in config and the port is set to the same on the vote sites.

**Comment by Zilacon** [comment]
Maybe it is conflicting with the UUID's? Like the website is sending the username Zilacon but its looking for a UUID instead?

**Comment by Poweruser** [comment]
Check the port that you have given the voting sites to connect to.
The "lost connection" information is part of the class LoginHandler, meaning that the voting site MC Index tries to connect to the main server port (where the game clients connect to), instead of Votifier's one

**Comment by Poweruser** [comment]
And I asked you copy all Votifier messages here. There are several already before votes are taken:

[Votifier] Enabling Votifier v1.9
[Votifier] DEBUG mode enabled!
[Votifier] ServerSocket is set up. Listening on Address: [ServerAddress here]
[Votifier] Votifier enabled.
[Votifier] VoteReceiver thread started. Votifier is now ready to receive incoming connections.

what about those?

**Comment by Zilacon** [comment]
[16:35:37 INFO]: [Votifier] Enabling Votifier v1.9
[16:35:37 INFO]: [Votifier] DEBUG mode enabled!
[16:35:37 INFO]: [Votifier] ServerSocket is set up. Listening on Address: /0.0.0.0:10010
[16:35:37 INFO]: [Votifier] Votifier enabled.
[16:35:37 INFO]: [Essentials] Enabling Essentials v2.13.1
[16:35:37 INFO]: [Votifier] VoteReceiver thread started. Votifier is now ready to receive incoming connections.

**Comment by Zilacon** [comment]
Problem solved.
