### ISSUE TITLE
New 1.7.9 build with mob changes.

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#6]
Hello. Currently we are using minetick as a testing platform to make our RPG plugin.
https://github.com/Zilacon/APOC-RPG

And since i saw you doing a bunch of tweaks to mobs and ai and our plugin will be dealing with editing mobs i was wondering if you could compile a 1.7.9 version of your recent changes to 1.7.2 minetick for me?

Thanks a lot!

**Comment by Poweruser** [comment]
Going to update the 1.7.9 branch with the latest additions from the 1.7.2 one ...

**Comment by Zilacon** [comment]
Thanks.

**Comment by Poweruser** [comment]
Done. As for handing out compiled kernels:  
`rant mode on`
I do not care about this dmca-crap, and my fork was not taken down. And I certainly do not respect the goals and doings of people that quit and then try to take down everyone and everything with them on their way out.
`rant mode off`  
So here you go, it's in the list of the releases (1.7.9-R0.2_r4)

**Comment by Zilacon** [comment]
Thanks a lot :)

Have you ever considered working together with the glowstone project? That way minetick would be 100% open source and you would not have to worry about bukkit. From what i can see the glowstone api is built kinda similar to minetick is. Per world threading.

Correct me if im wrong im not java savvy, got a programming team and help out with testing and ideas for the plugins/projects.

**Comment by Poweruser** [comment]
Do me a favor, will you? See how many zombies you can fight against in one world (normal one, not flatland) at the same time until the server brings up a "cant keep up" or you notice lag

**Comment by Zilacon** [comment]
Sure.
Do you want to see how many mobs the server can handle too? Or just how many i can fight?

**Comment by Poweruser** [comment]
Mainly how many path searching mobs the server can handle in one world. An estimate is good enough

**Comment by Zilacon** [comment]
500 zombies all trying to eat me... No lag at all.
700 zombies... Server gets a 3-5 second delay in issuing commands.

Still shows as 20 TPS on Essentials and Minetick
See if it can handle 1000...

**Comment by Zilacon** [comment]
I sat with the 700 for a while and the delay in server response increased to pretty much 1-3 minutes.

1000 zombies spawned in still didnt crash it, still says 20 tps.
But the delay in server response is so horrible gameplay is impossible.

**Comment by Poweruser** [comment]
I'm not quite sure what is causing that delay there, but I notice the same in my over-exaggerated tests

**Comment by Zilacon** [comment]
It also seems like once they "lock on" to a target they never "unlock". I moved away from my previous location and they are still trying to attack the area i was previously in.

I am not sure if this is due to the massive delay for the server or not.

**Comment by Poweruser** [comment]
On a wild guess, I'd say there's a queue somewhere that is processed at a fixed rate. And the heavy load we generate is filling it faster, than it is emptied. That would also explain the increase of the delay over time.

**Comment by Poweruser** [comment]
And I suspect it to be somewhere in the network code, and that the server cant send the accumulated mass of packets as fast as stuff is happening

**Comment by Zilacon** [comment]
Anyway to fix that?

Also is there anyway you could look into why chunks don't load or load 100x slower when you are flying? I can fly around and nothing loads, land and everything starts loading.

**Comment by Poweruser** [comment]
First I have to verify the source of the problem. I.e: Is it really the network code, that can not send all packets fast enough. Can be dis-/proven by having 2 players in different parts of the world, each being chased by 500 zombies. If the delay is gone, then its the network code that is not fast enough for 1000 zombies for a single client. If it's still happening, the search goes on. 

In case of the network code being the reason, I don't think I will try speeding it up, as I'd like to leave it alone. Instead I'll limit the number of entities a single client can track. By limiting/reducing that number, the number of packets should not go past the critical level anymore. 500+ zombies around one player is a total overkill anyways.

Chunk loading: will check. Please create a new issue/ticket for it as well. Makes it easier to find for other users, than with having multiple reports within one issue.

**Comment by Zilacon** [comment]
I really dont think theres ever going to be a situation where you got 500 zombies chasing you unless purposely spawned with plugin commands like i did.

**Comment by Poweruser** [comment]
2 players in seperate locations (same world) with each ~500 zombies, no delay
3 players in seperate locations (same world) with each ~400 zombies, no delay
our test server was in both cases starting to fall below 20tps
=> putting the EntityTracker on the todo-list
