### ISSUE TITLE
Forge compatibility?

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#9]
You mentioned you had BungeeCord compatibility into Minetick.

Well BungeeCord now has Forge support http://ci.md-5.net/job/BungeeCord/1013/

And since BungeeCord is a server jar could you not make a forge version of minetick by copying bungeecord?

**Comment by Poweruser** [comment]
> You mentioned you had BungeeCord compatibility into Minetick

Not yet

> And since BungeeCord is a server jar

No it's not, BungeeCord is the proxy that connects multiple servers.  
You seem to have misunderstood what Forge support for BungeeCord means. It means that the proxy can now properly connect multiple forge servers together.

Adding Forge to MinetickMod and hoping that all the different mods don't mind my changes, is a totally different story. Which I won't do by myself.

**Comment by Zilacon** [comment]
Ah i was under the impression BC was a whole server jar. I have never used it myself because i do not have the dedicated servers to have many servers of the same kind running.

I got a few people under my wing i will see if any of them are willing to do a MineTickForge project.

**Comment by daddysboy2001** [comment]
Wix?

**Comment by Zilacon** [comment]
What?
